print("Hello welcome to Google Cloud")
print("Hello welcome to Google Cloud")
print("Hello welcome to Google Cloud")
print("Hello welcome to Google Cloud")
print("Hello welcome to Google Cloud")
print("Hello welcome to Google Cloud")
